#server:
#  port: 8001
  
spring:
  application:
    name: item-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
---    
spring:
  profiles: itemservice1

server:
  port: 8001
  
---
spring:
  profiles: itemservice2

server:
  port: 8002